### ISSUE TITLE
Downloading directory when it's already been downloaded causes crash

### ISSUE THREAD

**Issue by rpenziol** [agile-pdx/FTPy#1]
To reproduce:
  Download directory from FTP server, then redownload the folder.

Notes:
  Problem does not appear to affect individual files.

Error appears to be in creating the directory:

Traceback (most recent call last):
  File "/home/robbie/Documents/FTPy/ftp.py", line 249, in <module>
    if **name** == '**main**': main()
  File "/home/robbie/Documents/FTPy/ftp.py", line 27, in main
    input_command = action(input_command, input_arg, sftp)#To use user command
  File "/home/robbie/Documents/FTPy/ftp.py", line 79, in action
    get_file(sftp, arg)
  File "/home/robbie/Documents/FTPy/ftp.py", line 185, in get_file
    sftp.get_r(download_queue[i], os.getcwd())
  File "/usr/local/lib/python2.7/dist-packages/pysftp.py", line 289, in get_r
    os.mkdir(reparent(localdir, subdir))
OSError: [Errno 17] File exists: '/home/robbie/Documents/FTPy/downloads/erikschmauss'

**Comment by rpenziol** [comment]
8 years and no resolution? *tisk*tisk*

If anyone gets a notice from this; I hope you're all doing well! 👋
